### PR TITLE
Dialog: Updated the content demo to mention new page attribute

### PR DESCRIPTION
**Pull request by agcolom**

### CODE REVIEW

**Comment by arthurvr** [comment]
Is this PR good to be merged?

**Comment by arschmitz** [comment]
@arthurvr yup

**Comment by arthurvr** [comment]
Well, somebody will need to do it then too... :) I can't.

**Comment by arschmitz** [comment]
@agcolom did you want to take care of this? If not I can.

**Comment by arthurvr** [comment]
ping @agcolom @arschmitz, can anyone of you take care of this?

**Comment by jaspermdegroot** [comment]
Bump

**Pull request merged**
